materialbatchedhsubexpapi:
# Listner details
  http:
    path: "/api/v1/dev/MaterialBatchEDHSubscriber_vs0/MaterialBatchEDHSubscriber_vs0_http1"

# API Autodiscovery details
  api:
    autodiscovery:
      id: "15559929"
      
# Web Service Consumer details      
  web:
    service: "#[vars.wsdlService]"
    port: "#[vars.wsdlPort]"
    address: "#[vars.wsdlAddress]"
    wsdl:
      name: "#[vars.wsdlName]"
# WSDL details for web service consumer 
  wsdl:
    target:
      name: "http://edhws-test.amgen.com:80/Amgen.ERP.MaterialBatch.Subscriber/MaterialBatchEDHSubscriber.asmx?wsdl"
      port: "MaterialBatchClientV1_0SOAP1"
      service: "SubscriberService"
      address: "http://edhws-test.amgen.com/Amgen.ERP.MaterialBatch.Subscriber/MaterialBatchEDHSubscriber.asmx" 
    source:
      name: "api/MaterialBatchService.wsdl"
      port: "MaterialBatchEDHSubscriber_vs0_http1"
      service: "MaterialBatchEDHSubscriber_vs0"      
      
#Logging details          
  main:
    organizationId: "amgen"
    level: "1.0"
    domainName: "gbs"
    logSuccessStatus: "Success"
    logInProcessStatus: "InProgress"
    logErrorStatus: "Error"
    integrationId: "INT020"
    integrationName: "materialBatchEDHSubExpApi" 
    processType: "materialBatchEDHSubExpApi"
    sourceSystemId: "SAP"
    destinationSystemId: "EDH"
  